spring:
  security:
    user:
      name: user
      password: pass
  datasource:
    url: jdbc:h2:mem:globomantics-toys
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console.enabled: false
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1


jwt.secret: "wToGV5RiWAU4UNQHJPVBXISBPNJ5C8yoiqbTRu5fXjM="


auth.cookie.hmac-key: "y.E@EA!FbtCwXYB-2v_n.!*xgzRqgtbq2d2_A_U!W2hubL@URHRzNP96WNPxEcXK"


server:
  error.whitelabel.enabled: false
  servlet.session.timeout: 1m
  port: 8080

springdoc:
  packagesToScan: io.globomantics.toystore.api
  pathsToMatch: /api/**
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
